package com.serverless;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

import java.io.IOException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Logger;

@DynamoDBTable(tableName = "Tasks")
public class Task {

    private static final String TASKS_TABLE_NAME = System.getenv("Tasks");

    private static DynamoDBAdapter db_adapter;
    private final AmazonDynamoDB client;
    private final DynamoDBMapper mapper;

    private Logger logger = Logger.getLogger(String.valueOf(this.getClass()));

    private String id;
    private String title;
//
//    @DynamoDBHashKey(attributeName = "dateStart")
//    private Date dateStart;
//
//    @DynamoDBHashKey(attributeName = "dateEnd")
//    private Date dateEnd;
//
//    @DynamoDBHashKey(attributeName = "description")
//    private String description;
//
//    @DynamoDBHashKey(attributeName = "done")
//    private Boolean done;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "title")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Task() {
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
                .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(TASKS_TABLE_NAME))
                .build();
        // get the db adapter
        this.db_adapter = DynamoDBAdapter.getInstance();
        this.client = this.db_adapter.getDbClient();
        // create the mapper with config
        this.mapper = this.db_adapter.createDbMapper(mapperConfig);
    }

    @Override
    public String toString() {
        return "Task{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                '}';
    }

    public void save(Task task) throws IOException {
        logger.info("Tasks - save(): " + task.toString());
        this.mapper.save(task);
    }

    public Task get(String id) throws IOException {
        Task task = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(id));

        DynamoDBQueryExpression<Task> queryExp = new DynamoDBQueryExpression<Task>()
                .withKeyConditionExpression("id = :v1")
                .withExpressionAttributeValues(av);

        PaginatedQueryList<Task> result = this.mapper.query(Task.class, queryExp);
        if (result.size() > 0) {
            task = result.get(0);
            logger.info("Tasks - get(): task - " + task.toString());
        } else {
            logger.info("Tasks - get(): task - Not Found.");
        }
        return task;
    }

    public List<Task> list() throws IOException {
        DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
        List<Task> results = this.mapper.scan(Task.class, scanExp);
        for (Task p : results) {
            logger.info("Task - list(): " + p.toString());
        }
        return results;
    }

    public Boolean delete(String id) throws IOException {
        Task task = null;

        // get product if exists
        task = get(id);
        if (task != null) {
            logger.info("Tasks - delete(): " + task.toString());
            this.mapper.delete(task);
        } else {
            logger.info("Tasks - delete(): product - does not exist.");
            return false;
        }
        return true;
    }


    //    public Date getDateStart() {
//        return dateStart;
//    }
//
//    public void setDateStart(Date dateStart) {
//        this.dateStart = dateStart;
//    }
//
//    public Date getDateEnd() {
//        return dateEnd;
//    }
//
//    public void setDateEnd(Date dateEnd) {
//        this.dateEnd = dateEnd;
//    }
//
//    public String getDescription() {
//        return description;
//    }
//
//    public void setDescription(String description) {
//        this.description = description;
//    }
//
//    public Boolean getDone() {
//        return done;
//    }
//
//    public void setDone(Boolean done) {
//        this.done = done;
//    }
}
